export { ListCustomers } from './list-customers'
export { ListCustomersByGender } from './list-customers-by-gender'
export { ListCustomersByMostConsumptionAndGenderUseCase } from './list-customers-by-most-consumption-and-gender'
export { ListProductsAndServicesByMostConsumption } from './list-products-and-services-by-most-comsumption'
export { ListCustomersByMostConsumption } from './list-customers-by-most-consumption'
export { ListCustomersByLessConsumption } from './list-customers-by-less-consumption'
export { ListCustomersByMostSpeding } from './list-customers-by-most-spending'

export { ListProducts } from './list-products'
export { ListServices } from './list-services'
