export { ListCustomersByGenderController } from './list-customers-by-gender-controller'
export { ListCustomersByLessConsumptionController } from './list-customers-by-less-consumption-controller'
export { ListCustomersByMostConsumptionController } from './list-customers-by-most-consumption-controller'
export { ListCustomersByMostSpendingController } from './list-customers-by-most-spending-controller'
export { ListMostConsumedProductsController } from './list-most-consumed-products-controller'
export { ListMostConsumedServicesController } from './list-most-consumed-services-controller'
